{% set name = "contexter" %}
{% set version = "0.1.4" %}
{% set sha256 = "c730890b1a915051414a6350d8ea1cddca7d01d8f756badedb30b9bf305ea0a8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: "python"
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

about:
  home: "https://bitbucket.org/defnull/contexter"
  license: "MIT"
  license_family: "MIT"
  license_file: LICENSE.txt
  summary: "Contexter: A better contextlib"
  description: "Contexter is a full replacement of the contextlib standard library
module. It comes with more features, a nicer API and full support for
Python 2.5 up to 3.x from a single source file."

